version: "3"
volumes:
   pgdata:
     driver: "local"
services:
  my-db:
    build: ./Docker/db
    container_name: "my-db"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "dev"
      POSTGRES_PASSWORD: "secret"
    command: 'postgres -c config_file="/etc/postgresql.conf"'
    volumes:
      - "pgdata:/var/lib/postgresql/data"
      - "./Docker/db/conf/postgresql.conf:/etc/postgresql.conf"
      - "./Docker/db/sql:/docker-entrypoint-initdb.d"